name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Compile Java
        run: javac src/Calculator.java

      - name: Run application
        run: java -cp src Calculator
- name: Run Unit Test
  run: |
    javac -cp src src/CalculatorTest.java
    java -cp src CalculatorTest